services:
  postgres:
    container_name: marvel-heroes-db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: marvel_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: codigo1234
    ports:
      - "5432:5432"
    networks:
      - springboot-network

  redis:
    container_name: marvel-heroes-redis
    image: redis:latest
    command: redis-server
    ports:
      - "6379:6379"
    restart: always
    networks:
      - springboot-network

  springboot:
    container_name: marvel-heroes-web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      - LANG=pt_BR.UTF-8
      - JAVA_HOME=/usr/java/jdk-21
      - PATH=$JAVA_HOME/bin:$PATH
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - springboot-network
    depends_on:
      - postgres
      - redis

networks:
  springboot-network:
    driver: bridge
